version: "3.8"

services:
  order-service:
    build:
      context: ./backend/order-service
    ports:
      - "8000:8000"
    env_file:
      - ./backend/order-service/.env
    depends_on:
      - mongo
    networks:
      - app-network

  payment-service:
    build:
      context: ./backend/payment-service
    ports:
      - "8001:8001"
    env_file:
      - ./backend/payment-service/.env
    depends_on:
      - mongo
    networks:
      - app-network

  auth-service:
      build:
        context: ./backend/auth-service
      ports:
        - "5000:5000"
      env_file:
        - ./backend/auth-service/.env
      depends_on:
        - mongo
      networks:
        - app-network
    
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:

